// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/SahilBheke25/ResourceSharingApplication/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// RentEquipment provides a mock function with given fields: ctx, _a1
func (_m *Service) RentEquipment(ctx context.Context, _a1 models.Rental) (models.Billing, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RentEquipment")
	}

	var r0 models.Billing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Rental) (models.Billing, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Rental) models.Billing); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(models.Billing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Rental) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
